"""S1.7: build the Workspace Tool adapter and its manifest.

Two builds, one source. The service lives in Git and is tested there; the
Workspace Tool is an artefact generated from it, and the artefact is what Open
WebUI stores in `webui.db` and loads. This script is the only thing that writes
that artefact, so the DB copy has a provenance and a digest instead of being a
file somebody pasted.

What the adapter is allowed to contain is fixed by CORE-BOUNDARY-01: argument
coercion, a call into the service, and the terminal envelope. Source policy,
owner parsing, retry and audit are forbidden inside it -- and since the adapter
is generated rather than written, that is a property of this script rather than
a rule someone has to keep remembering.

The method is `fill_geoteaser`, not `fill_geotizer`. That name belongs to the
Skills and the system prompts that call it (`GMM` attention register A-23 records
that the monolith's own header comment gets it wrong), and §8 says never rename a
string you do not own.

Docstrings are the tool schema: Open WebUI generates the JSON schema the model
sees from the method docstring and type hints, so the docstring below is a
contract and the manifest records the spec it produces.

Usage:
    PYTHONPATH=backend python scripts/build_geotizer_tool.py [--output-dir dist]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / 'backend'))

TOOL_ID = 'geoteaser'
TOOL_NAME = 'GeoTeaser'
TOOL_VERSION = '3.0.0'
DEFAULT_OUTPUT_DIR = REPO_ROOT / 'dist'
ARTIFACT_NAME = 'geoteaser_tool.py'
MANIFEST_NAME = 'geoteaser_tool.manifest.json'

# The adapter, verbatim. Everything it does is coerce, delegate and hand back.
ADAPTER = '''"""
title: GeoTeaser
author: GeoMAS
version: {version}
required_open_webui_version: 0.10.0
"""

# Generated by scripts/build_geotizer_tool.py from {source_repository}@{source_commit}.
# Do not edit in the Workspace. Edit the service in Git and rebuild: an edit here
# is invisible to CI and to every test, which is the failure §9 blocks release on.

from typing import Any

from open_webui.tools.geotizer import fill_geotizer


class Tools:
    def __init__(self):
        # Custom `source` events are emitted by the service; leaving automatic
        # citations on would replace them.
        self.citation = False

    async def fill_geoteaser(
        self,
        object_name: str,
        project_id: str = "",
        model_run_id: str = "",
        run_id: str = "",
        allow_draft: bool = True,
        vision_collection_url: str = "",
        __request__: Any = None,
        __user__: dict = None,
        __event_emitter__: Any = None,
        __event_call__: Any = None,
        __metadata__: dict = None,
        __chat_id__: str = None,
        __message_id__: str = None,
        __model_knowledge__: list = None,
        __files__: list = None,
    ) -> str:
        """Fill GeoTeaser Object through the deterministic GIS state machine.

        Use this function for a user request such as "Заполни Геотизер для ...".
        It is the only tool the parent model should call for the complete workflow:
        the function resolves the GIS project, collects bounded KB/WEB/GIS evidence,
        submits all exact-owner batches, runs the final audit and returns a download
        link for the rendered XLSX. Do not call specialist or Excel tools manually
        before or after this function.

        :param object_name: Geological object or licence-area name.
        :param project_id: Optional exact linked GIS project ID.
        :param model_run_id: Optional exact DataCube run ID.
        :param run_id: Optional existing GeoTeaser run ID to resume.
        :param allow_draft: Allow final XLSX with explicit data gaps.
        :param vision_collection_url: Optional exact Open WebUI collection URL or
            ID containing project-specific maps and sections.
        :return: Markdown result with completeness counts and XLSX download link.
        """
        return await fill_geotizer(
            object_name=object_name,
            project_id=project_id,
            model_run_id=model_run_id,
            run_id=run_id,
            allow_draft=allow_draft,
            vision_collection_url=vision_collection_url,
            __request__=__request__,
            __user__=__user__,
            __event_emitter__=__event_emitter__,
            __event_call__=__event_call__,
            __metadata__=__metadata__,
            __chat_id__=__chat_id__,
            __message_id__=__message_id__,
            __model_knowledge__=__model_knowledge__,
            __files__=__files__,
        )
'''


def source_commit() -> str:
    return subprocess.run(
        ['git', '-C', str(REPO_ROOT), 'rev-parse', 'HEAD'],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()


def render(commit: str) -> str:
    return ADAPTER.format(
        version=TOOL_VERSION,
        source_repository='data-satanism/open-webui-geo',
        source_commit=commit,
    )


class SpecUnavailable(RuntimeError):
    pass


def tool_spec(content: str) -> list[dict]:
    """The schema the model will see, generated the way Open WebUI generates it.

    Recorded in the manifest because the docstring *is* the contract: a prose
    edit changes what the model is told the tool does, and a diff of the spec is
    the only place that shows up.

    Generating it needs `open_webui.utils.tools`, which pulls in the retrieval
    stack and so the full `backend/requirements.txt`. Where that is not
    installed the build refuses rather than writing a manifest with a hole in
    it; `--allow-missing-spec` records the absence and its reason, and is for a
    developer machine, never for a release build.
    """
    try:
        from open_webui.utils.tools import get_tool_specs
    except ImportError as exc:  # pragma: no cover - depends on the environment
        raise SpecUnavailable(str(exc)) from exc

    namespace: dict = {}
    exec(compile(content, ARTIFACT_NAME, 'exec'), namespace)
    return get_tool_specs(namespace['Tools']())


def build(output_dir: Path, commit: str | None = None, *, allow_missing_spec: bool = False) -> dict:
    commit = commit or source_commit()
    content = render(commit)
    raw = content.encode('utf-8')

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / ARTIFACT_NAME).write_text(content, encoding='utf-8')

    manifest = {
        'schema_version': 1,
        'tool_id': TOOL_ID,
        'name': TOOL_NAME,
        'version': TOOL_VERSION,
        'artifact': ARTIFACT_NAME,
        'sha256': hashlib.sha256(raw).hexdigest(),
        'bytes': len(raw),
        'source_repository': 'data-satanism/open-webui-geo',
        'source_commit': commit,
        'entrypoint': 'fill_geoteaser',
        'required_open_webui_version': '0.10.0',
    }
    try:
        manifest['spec'] = tool_spec(content)
        manifest['spec_unavailable_because'] = None
    except SpecUnavailable as exc:
        if not allow_missing_spec:
            raise
        manifest['spec'] = None
        manifest['spec_unavailable_because'] = f'{exc}; install backend/requirements.txt to record it'

    (output_dir / MANIFEST_NAME).write_text(
        json.dumps(manifest, ensure_ascii=False, indent=1, sort_keys=False) + '\n',
        encoding='utf-8',
    )
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output-dir', type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        '--allow-missing-spec',
        action='store_true',
        help='record the tool spec as unavailable instead of failing. Developer machines only.',
    )
    args = parser.parse_args()

    manifest = build(args.output_dir, allow_missing_spec=args.allow_missing_spec)
    spec = manifest['spec']
    print(
        f'{args.output_dir / ARTIFACT_NAME}: {manifest["name"]} {manifest["version"]}, '
        f'sha256 {manifest["sha256"][:12]}, {manifest["bytes"]} bytes, '
        f'{len(spec) if spec is not None else "no"} tool spec(s) from {manifest["source_commit"][:8]}'
    )
    if spec is None:
        print(f'  WARNING: {manifest["spec_unavailable_because"]}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
